{{- if .Values.ingress.enabled -}}
{{- $fullName := include "ingress-duplication.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: main-deployment
  labels:
    {{- include "ingress-duplication.labels" . | nindent 4 }}
  annotations:
#    These annotations allow replication of a service to a different location. Responses from the replica
#    service are discarded.
    nginx.ingress.kubernetes.io/configuration-snippet: |
      mirror /mirror;
# The proxy_pass directive uses the hard-coded ip of the service and will need updating.  We ought to be using the host
# 'replicated-deployment.local' here but for some reason the k8s DNS isn't resolving it in minikube. The principle works though.
# This X-Shadow-Service header is optional
    nginx.ingress.kubernetes.io/server-snippet: |
      location = /mirror {
          internal;
          set $shadow_service_name    "main-deployment";
          proxy_set_header X-Shadow-Service  $shadow_service_name;
          proxy_pass http://10.106.186.91$request_uri;
      }
spec:
  rules:
    - host: main-deployment.local
      http:
        paths:
          - path: /
            backend:
              serviceName: main-deployment
              servicePort: {{ $svcPort }}
{{- end }}
