{{- if .Values.ingress.enabled -}}
{{- $fullName := include "ingress-duplication.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: replicated-deployment
  labels:
    {{- include "ingress-duplication.labels" . | nindent 4 }}
  annotations:
#    This annotation in combination with the regex in the path (see ⭐️) allows capturing parts of the original path
#    and rewriting it to something that suits us better using the placeholder $2
    nginx.ingress.kubernetes.io/rewrite-target: /whatever/we/$2/please/
spec:
  rules:
    - host: replicated-deployment.local
      http:
        paths:
#          ⭐️ Everything after 'something' will be captured and replaced into the rewritten url at $2
          - path: /something(/|$)(.*)
            backend:
              serviceName: replicated-deployment
              servicePort: {{ $svcPort }}
{{- end }}
