apiVersion: v1
kind: Service
metadata:
  name: main-deployment
  labels:
    {{- include "ingress-duplication.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: main-deployment
    app.kubernetes.io/instance: {{ .Release.Name }}
